### ISSUE TITLE
What are the minimal needed permissions using a PAT

### ISSUE THREAD

**Issue by service-paradis** [srggrs/assign-one-project-github-action#58]
We want to use this action to add PRs from a repo to an organisation project.
We want to know what are the minimal permissions needed.

 - `write:org`?
 - `read:org`?
 - `admin:org`?
 - other?

**Comment by ian-whitestone** [comment]
Related https://github.com/srggrs/assign-one-project-github-action/issues/61

**Comment by service-paradis** [comment]
`secrets.GITHUB_TOKEN` is working fine if the project is in the same repo.
In our case, we want to use the project at the organisation level. Looks like we need a PAT to make this work.

**Comment by srggrs** [comment]
I think you need the `write:org` and `read:org` for sure, then follow the instructions in https://github.com/srggrs/assign-one-project-github-action#organisation-or-user-project

**Comment by service-paradis** [comment]
Yes, I can make it works using the instructions.
I just wanted to know the minimal required permissions to limit the scope of the PAT.

Thank you for the follow up!

**Comment by gilgongo** [comment]
@service-paradis 

> In our case, we want to use the project at the organisation level. Looks like we need a PAT to make this work.

Do you have an example how to use a PAT in the script?

**Comment by brandonh-msft** [comment]
> `secrets.GITHUB_TOKEN` is working fine if the project is in the same repo. In our case, we want to use the project at the organisation level. Looks like we need a PAT to make this work.

These instructions only say to gen a token - they don't say the scope needed for said token.
