### ISSUE TITLE
Question: How to assign project when issue is assigned to someone

### ISSUE THREAD

**Issue by flisboac** [srggrs/assign-one-project-github-action#84]
Hello, thanks for this amazing action! I'm already using it to assign a default project to all new issues, but I've been thinking if there's any way to assign a different column in this same project at the moment some repo/org member is assigned to the issue (be it new, or existing).

Also, is there any documentation or guidelines on how to configure the workflow triggers (e.g. which `types` are available for each `on` trigger).

**Comment by srggrs** [comment]
Probably there is... I think you need to have a look at the GitHub action triggers https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows

**Comment by flisboac** [comment]
Nice, thanks!

I'm new to Github Actions. The trigger part of a workflow doesn't even concern the actions it calls. That was some misunderstanding on my part.

I also suppose the `if` in the action's configuration follows the payload sent to the workflow, and that's documented as well (I suppose [here](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads)).

Going to take a look on that as soon as I get time again. I'll update the issue as soon as I find my solution.
